// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: service_two/service_two.proto

package service_two

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceTwoClient is the client API for ServiceTwo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceTwoClient interface {
	SayHelloServiceTwo(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type serviceTwoClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceTwoClient(cc grpc.ClientConnInterface) ServiceTwoClient {
	return &serviceTwoClient{cc}
}

func (c *serviceTwoClient) SayHelloServiceTwo(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/serviceTwo.ServiceTwo/SayHelloServiceTwo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceTwoServer is the server API for ServiceTwo service.
// All implementations must embed UnimplementedServiceTwoServer
// for forward compatibility
type ServiceTwoServer interface {
	SayHelloServiceTwo(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedServiceTwoServer()
}

// UnimplementedServiceTwoServer must be embedded to have forward compatible implementations.
type UnimplementedServiceTwoServer struct {
}

func (UnimplementedServiceTwoServer) SayHelloServiceTwo(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloServiceTwo not implemented")
}
func (UnimplementedServiceTwoServer) mustEmbedUnimplementedServiceTwoServer() {}

// UnsafeServiceTwoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceTwoServer will
// result in compilation errors.
type UnsafeServiceTwoServer interface {
	mustEmbedUnimplementedServiceTwoServer()
}

func RegisterServiceTwoServer(s grpc.ServiceRegistrar, srv ServiceTwoServer) {
	s.RegisterService(&ServiceTwo_ServiceDesc, srv)
}

func _ServiceTwo_SayHelloServiceTwo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceTwoServer).SayHelloServiceTwo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviceTwo.ServiceTwo/SayHelloServiceTwo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceTwoServer).SayHelloServiceTwo(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceTwo_ServiceDesc is the grpc.ServiceDesc for ServiceTwo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceTwo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceTwo.ServiceTwo",
	HandlerType: (*ServiceTwoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloServiceTwo",
			Handler:    _ServiceTwo_SayHelloServiceTwo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_two/service_two.proto",
}
