// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.2
// source: service_one/service_one.proto

package service_one

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceOneClient is the client API for ServiceOne service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceOneClient interface {
	SayHelloServiceOne(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type serviceOneClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceOneClient(cc grpc.ClientConnInterface) ServiceOneClient {
	return &serviceOneClient{cc}
}

func (c *serviceOneClient) SayHelloServiceOne(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/serviceOne.ServiceOne/SayHelloServiceOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceOneServer is the server API for ServiceOne service.
// All implementations must embed UnimplementedServiceOneServer
// for forward compatibility
type ServiceOneServer interface {
	SayHelloServiceOne(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedServiceOneServer()
}

// UnimplementedServiceOneServer must be embedded to have forward compatible implementations.
type UnimplementedServiceOneServer struct {
}

func (UnimplementedServiceOneServer) SayHelloServiceOne(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHelloServiceOne not implemented")
}
func (UnimplementedServiceOneServer) mustEmbedUnimplementedServiceOneServer() {}

// UnsafeServiceOneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceOneServer will
// result in compilation errors.
type UnsafeServiceOneServer interface {
	mustEmbedUnimplementedServiceOneServer()
}

func RegisterServiceOneServer(s grpc.ServiceRegistrar, srv ServiceOneServer) {
	s.RegisterService(&ServiceOne_ServiceDesc, srv)
}

func _ServiceOne_SayHelloServiceOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceOneServer).SayHelloServiceOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serviceOne.ServiceOne/SayHelloServiceOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceOneServer).SayHelloServiceOne(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceOne_ServiceDesc is the grpc.ServiceDesc for ServiceOne service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceOne_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviceOne.ServiceOne",
	HandlerType: (*ServiceOneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHelloServiceOne",
			Handler:    _ServiceOne_SayHelloServiceOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_one/service_one.proto",
}
